# Generated by Django 3.2.25 on 2025-04-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tarefa', max_length=20)),
                ('checked', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='checked',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='session_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='donesession',
            name='duration',
            field=models.DurationField(),
        ),
    ]
