# Generated by Django 3.2.25 on 2025-04-17 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20250408_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='main.session'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donesession',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.session'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
