# Generated by Django 3.2.25 on 2025-06-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250417_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='position',
            field=models.CharField(default='midrange-c', max_length=50),
        ),
        migrations.AlterField(
            model_name='donesession',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
