# Generated by Django 5.2.2 on 2025-06-10 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20250609_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donesession',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.session'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='position',
            field=models.CharField(default='midrange-r', max_length=50),
        ),
    ]
