# Generated by Django 3.2.25 on 2025-06-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_donesession_session_alter_exercise_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('reps', models.IntegerField()),
                ('makes', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('done_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done_exercises', to='main.donesession')),
            ],
        ),
    ]
